export const BASE_URL = 'https://sirenalifestyle.com'
//export const BASE_URL= 'http://staging.sirena.binaural.com.ve:8480'
//export const BASE_URL= 'http://192.168.0.26:8000'
//export const BASE_URL= 'http://qa2.sirena.binaural.com.ve:8480'
const API_URL = '/api'
export const LOGIN_URL = BASE_URL + API_URL+'/login'
export const FORGOT_URL = BASE_URL + API_URL+'/password/reset'
export const CLIENTS_URL = BASE_URL + API_URL + '/users'
export const BALANCE_URL= CLIENTS_URL+'/balance/'
export const LIST_CLIENTS_URL=CLIENTS_URL+"/potencialUserList/"
export const VISITS=BASE_URL+API_URL+'/users/visitsForUserSeller/'
export const UPDATE_VISIT= BASE_URL+API_URL+'/visits/updateAfterVisit'
export const CLIENT_FORM = BASE_URL + '/users/form/'
export const FIND_CLIENT_BY_CELL = CLIENTS_URL + '/showByCell?cell='
export const FIND_CLIENT_BY_EMAIL = CLIENTS_URL + '/showByEmail?fetch=all&email='
export const LANGUAGE = BASE_URL + API_URL+ '/languages'
